### PR TITLE
Revert " op3(t): rename frp partition to the correct name "

### PR DESCRIPTION
**Pull request by rlcDev**
This reverts commit 9c6c3209920043aa303ad7744e388df9a3ba5945

### CODE REVIEW

**Comment by maxwen** [comment]
Why is frp wrong and config correct?

**Comment by rlcDev** [comment]
Since it incurs this error :
Error: could not load context file from ../OmniRom/out/target/product/oneplus3/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp

Edit : on oneplus3 compilation

**Comment by maxwen** [comment]
You should do a clean build

**Comment by rlcDev** [comment]
I tried to make clean builds many times. (for oneplus3)
When getting back to "config", compilation is successful.
But I will try again and see.
Thanks

**Comment by maxwen** [comment]
Will be solved different https://gerrit.omnirom.org/#/c/21532/

**Pull request closed without merging**
